//
// Created by uqamportable on 02/08/18.
//

#ifndef IMAGEREC_VIDEOFEEDTYPES_H
#define IMAGEREC_VIDEOFEEDTYPES_H

enum class VideoFeedTypes {VIDEO=0,REALSENSE=1,KINECT=2,WEBCAM=3,NONE=4};


#endif //IMAGEREC_VIDEOFEEDTYPES_H
