// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "inkpicture1.h"

/////////////////////////////////////////////////////////////////////////////
// CInkpicture1

IMPLEMENT_DYNCREATE(CInkpicture1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CInkpicture1 properties

/////////////////////////////////////////////////////////////////////////////
// CInkpicture1 operations
