.TH "controller Directory Reference" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBManageSourceVideo\&.h\fP"
.br
.RI "Select the good source video including size and handle update\&. "
.in -1c
