.TH "model/recoActivite/recoImage Directory Reference" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/recoActivite/recoImage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBActivityRegion\&.h\fP"
.br
.RI "interact with YOLO which gives detected objects and hands "
.ti -1c
.RI "file \fBDetectedObject\&.h\fP"
.br
.RI "3 class : \fBDetectedMatrice\fP, \fBDetectedObject\fP, \fBDetectedObjects\fP "
.in -1c
