.TH "model/recoActivite/recoImage/ActivityRegion.h" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/recoActivite/recoImage/ActivityRegion.h \- interact with YOLO which gives detected objects and hands  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'DetectedObject\&.h'\fP
.br
\fC#include 'selectiveSearchDepth\&.h'\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <future>\fP
.br
\fC#include 'cnn/YoloGPU\&.h'\fP
.br
\fC#include 'cnn/YoloCPU\&.h'\fP
.br
\fC#include <stack>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActivityRegion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
interact with YOLO which gives detected objects and hands 


.PP
\fBAuthor:\fP
.RS 4
Mathieu Gravel 
.RE
.PP
\fBVersion:\fP
.RS 4
2\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
8 August 2019 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
