.TH "bnf::_Ctrl< flg, cc >" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bnf::_Ctrl< flg, cc >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbnf::_Tie\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fB_parse\fP (\fB_Base\fP *parser) const  throw ()"
.br
.ti -1c
.RI "\fB_Ctrl\fP (const \fB_Ctrl\fP *ctrl)"
.br
.ti -1c
.RI "\fB_Ctrl\fP (const \fB_Ctrl\fP &control)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB_Tie\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
