.TH "bnf::Lexem" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bnf::Lexem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbnf::_Tie\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLexem\fP (const char *literal, bool cs=0)"
.br
.ti -1c
.RI "\fBLexem\fP (const \fB_Tie\fP &link)"
.br
.ti -1c
.RI "\fBLexem\fP & \fBoperator=\fP (const \fBLexem\fP &lexem)"
.br
.ti -1c
.RI "\fBLexem\fP & \fBoperator=\fP (const \fB_Tie\fP &link)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLexem\fP (\fBLexem\fP *lxm)"
.br
.ti -1c
.RI "virtual int \fB_parse\fP (\fB_Base\fP *parser) const  throw ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB_Tie\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
