.TH "DetectedMatrices" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DetectedMatrices
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDetectedMatrices\fP (std::vector< \fBDetectedMatrice\fP > &objets)"
.br
.ti -1c
.RI "const std::vector< \fBDetectedMatrice\fP > & \fBgetMatrices\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
