.TH "DetectedMatrice" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DetectedMatrice
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDetectedMatrice\fP (cv::Rect position, Predictions &pre, double _dist)"
.br
.ti -1c
.RI "const cv::Rect & \fBgetObjPos\fP () const"
.br
.ti -1c
.RI "const Predictions & \fBgetPredictions\fP () const"
.br
.ti -1c
.RI "const float \fBgetClassPrediction\fP (const std::string &className) const"
.br
.ti -1c
.RI "const double & \fBgetDist\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
