.TH "controller/ManageSourceVideo.h" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller/ManageSourceVideo.h \- Select the good source video including size and handle update\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'sources/VideoSource\&.h'\fP
.br
\fC#include 'sources/RealSense\&.h'\fP
.br
\fC#include 'sources/RealSenseVideo\&.h'\fP
.br
\fC#include 'sources/Kinect\&.h'\fP
.br
\fC#include 'sources/WebCam\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br
\fC#include <list>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'Subject\&.h'\fP
.br
\fC#include '\&.\&./model/Observer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBManageSourceVideo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Select the good source video including size and handle update\&. 


.PP
\fBAuthor:\fP
.RS 4
Mathieu Gravel 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
13 June 2019 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
