.TH "model/recoActivite/recoAffordance/MatriceAffordance.h" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/recoActivite/recoAffordance/MatriceAffordance.h \- keep in memory the last affordances seen (frame in the last 800ms : in version 2\&.0) PUT in cpp  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <stack>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'Affordance\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatriceAffordance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
keep in memory the last affordances seen (frame in the last 800ms : in version 2\&.0) PUT in cpp 


.PP
\fBAuthor:\fP
.RS 4

.RE
.PP
\fBVersion:\fP
.RS 4
2\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
14/08/2019 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
