.TH "md__r_e_a_d_m_e" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_eReconnaissance de plans et d'activités 
 \- Application de reconnaissance de plans et d'activités pour un robot assistant\&.
.PP
Développée pour un projet de recherche du \fCLaboratoire de recherche en Gestion, Diffusion et Acquisition des Connaissances\fP (GDAC-LIA) de l'\fCUniversité du Québec à Montréal\fP (UQAM)\&. Le projet est porté par le réseau de recherche d'\fCAGE-WELL\fP (Aging Gracefully across Environments using Technology to Support Wellness, Engagement and Long Life) financé par les \fCRéseaux de Centres d'Excellence du Canada\fP (Gouvernement du Canada)\&.
.PP
.SS "Dépendances"
.PP
.IP "\(bu" 2
C++ 11
.IP "\(bu" 2
CMake 3
.IP "\(bu" 2
Python 3
.IP "\(bu" 2
Qt 5
.IP "\(bu" 2
OpenCV 3
.IP "\(bu" 2
Intel RealSense 2
.IP "\(bu" 2
Darknet
.PP
.PP
Les dépendances peuvent être installées en exécutant le script suivant (10 Go seront nécessaires pendant l'installation) :
.PP
.PP
.nf
sudo sh install\&.sh
.fi
.PP
.PP
.SS "Usage"
.PP
Ce programme peut être compilé et testé par les commandes :
.PP
.PP
.nf
cd build
cmake \&.\&.
make
 \&./ImageRec
.fi
.PP
.PP
.SS "License"
.PP
\&.\&.\&.
.PP
.SS "References"
.PP
.SH "\&.\&.\&. "
.PP
.PP
L'application peut être lancée par la commande suivante :
.PP
.PP
.nf
\&./src/reconnaissance-plans-activites
.fi
.PP
.PP
.SS "Remerciements"
.PP
.IP "\(bu" 2
Éric Beaudry, Professeur agrégé (UQAM, Canada)
.IP "\(bu" 2
Jean Massardi, Doctorant (UQAM, Canada)
.IP "\(bu" 2
Mathieu Gravel, Étudiant en maîtrise (UQAM, Canada)
.IP "\(bu" 2
Baptiste Gauthier, Étudiant ingénieur (Polytech Nantes, France)
.IP "\(bu" 2
Philippe Billard, Étudiant ingénieur (Exia Cesi d'Orléans, France)
.IP "\(bu" 2
Guillaume Gosset, Étudiant (IUT d'Orsay, France) 
.PP

