.TH "Observer" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Observer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Observer\&.h>\fP
.PP
Inherited by \fBRecognitionManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdateByObservee\fP (cv::Mat imageColor, cv::Mat imageDepth)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for the \fBObserver\fP 
.SH "Member Function Documentation"
.PP 
.SS "virtual void Observer::updateByObservee (cv::Mat imageColor, cv::Mat imageDepth)\fC [pure virtual]\fP"
Update the state of this observer 
.PP
\fBParameters:\fP
.RS 4
\fItest\fP entier de test 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
