.TH "model/recoPlan/PARC/include/planLibrary.h" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/recoPlan/PARC/include/planLibrary.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <unordered_set>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'rule\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBplanLibrary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jean Massardi 
.RE
.PP
\fBVersion:\fP
.RS 4
2\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
8 August 2019 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
