.TH "RealSenseVideo" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RealSenseVideo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVideoSource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRealSenseVideo\fP (std::string colorFile='', std::string depthFile='')"
.br
.ti -1c
.RI "cv::Mat \fBgetColorFeed\fP ()"
.br
.ti -1c
.RI "cv::Mat \fBgetDepthFeed\fP ()"
.br
.ti -1c
.RI "cv::Mat \fBgetMappedFeed\fP ()"
.br
.ti -1c
.RI "cv::Mat \fBgetOriginalDepth\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "bool \fBhasDepthSource\fP ()"
.br
.ti -1c
.RI "std::string \fBgetTimeStamp\fP ()"
.br
.ti -1c
.RI "int \fBgetTimePosition\fP ()"
.br
.ti -1c
.RI "double \fBgetExactTimePosition\fP ()"
.br
.ti -1c
.RI "std::pair< int, int > \fBgetScreenSize\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
