.TH "selectiveDepth::Universe" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
selectiveDepth::Universe
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniverse\fP (int num)"
.br
.ti -1c
.RI "int \fBfind\fP (int x)"
.br
.ti -1c
.RI "void \fBjoin\fP (int x, int y)"
.br
.ti -1c
.RI "int \fBsize\fP (int x) const"
.br
.ti -1c
.RI "int \fBnumSets\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
