.TH "selectiveDepth::UniverseElement" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
selectiveDepth::UniverseElement
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniverseElement\fP (int rank, int size, int p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBrank\fP"
.br
.ti -1c
.RI "int \fBp\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
