.TH "selectiveDepth::edge" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
selectiveDepth::edge
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBa\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.ti -1c
.RI "double \fBw\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
