.TH "solverParticle" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solverParticle
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsolverParticle\fP (\fBextendedPlanLibrary\fP *_epl)"
.br
.ti -1c
.RI "bool \fBupdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBextendedPlanLibrary\fP * \fBepl\fP"
.br
.ti -1c
.RI "int \fBgoal\fP"
.br
.ti -1c
.RI "vector< int > \fBexpNextObs\fP"
.br
.ti -1c
.RI "\fBtree\fP \fBplanTree\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
