.TH "std" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhash< rule >\fP"
.br
.ti -1c
.RI "class \fBhash< std::pair< int, int > >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Selective search Depth Code de l'algorithme selective search depth, base sur l'implementation de l'algorithme Selective Search La version originale est prise de https://github.com/watanika/selective-search-cpp 
.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
