.TH "testSolver" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testSolver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSolver\fP (int _nbTest)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "void \fBaddSolver\fP (\fBsolver\fP s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
