.TH "Yolo" 3 "Mon Aug 19 2019" "plan recognition algorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Yolo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDetector\fP\&.
.PP
Inherited by \fBYoloCPU\fP, and \fBYoloGPU\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for plan recognition algorithms from the source code\&.
